on: [push]

name: CI

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Operating System dependencies
        run: sudo apt-get update -y && sudo apt-get install -y build-essential
      - name: Enable Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run build check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
